### PR TITLE
Upgraded to .NET 8 

### PR DESCRIPTION
**Pull request by davidop**
Update target framework versions and package references

### CODE REVIEW

**Comment by davidop** [comment]
This PR solves #517

**Comment by davidop** [comment]
@microsoft-github-policy-service agree

**Comment by Beelzenef** [comment]
Is it good for merging, @FBoucher? would be lovely!

**Review by FBoucher — APPROVED** [review]
LGTM 🎯

**Comment by FBoucher** [comment]
@allcontributors add @davidop as a contributor for code

**Pull request merged**
